import type { Paper } from './supabase/types'

export const seedPapers: Omit<Paper, 'id' | 'created_at' | 'updated_at'>[] = [
  {
    title: 'Data Structures and Algorithms - End Semester 2023',
    subject: 'Data Structures and Algorithms',
    branch: 'CSE',
    year: 2023,
    semester: 3,
    exam_type: 'End-Sem',
    pdf_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    slug: 'dsa-end-sem-2023-cse-s3',
    download_count: 312,
  },
  {
    title: 'Operating Systems - Mid Semester 2023',
    subject: 'Operating Systems',
    branch: 'CSE',
    year: 2023,
    semester: 5,
    exam_type: 'Mid-Sem',
    pdf_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    slug: 'os-mid-sem-2023-cse-s5',
    download_count: 198,
  },
  {
    title: 'Computer Networks - End Semester 2022',
    subject: 'Computer Networks',
    branch: 'CSE',
    year: 2022,
    semester: 6,
    exam_type: 'End-Sem',
    pdf_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    slug: 'cn-end-sem-2022-cse-s6',
    download_count: 245,
  },
  {
    title: 'Database Management Systems - Mid Semester 2022',
    subject: 'Database Management Systems',
    branch: 'CSE',
    year: 2022,
    semester: 4,
    exam_type: 'Mid-Sem',
    pdf_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    slug: 'dbms-mid-sem-2022-cse-s4',
    download_count: 179,
  },
  {
    title: 'Analog Circuits - End Semester 2023',
    subject: 'Analog Circuits',
    branch: 'ECE',
    year: 2023,
    semester: 4,
    exam_type: 'End-Sem',
    pdf_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    slug: 'analog-circuits-end-sem-2023-ece-s4',
    download_count: 143,
  },
  {
    title: 'Digital Signal Processing - Mid Semester 2023',
    subject: 'Digital Signal Processing',
    branch: 'ECE',
    year: 2023,
    semester: 6,
    exam_type: 'Mid-Sem',
    pdf_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    slug: 'dsp-mid-sem-2023-ece-s6',
    download_count: 121,
  },
  {
    title: 'Electromagnetic Theory - End Semester 2022',
    subject: 'Electromagnetic Theory',
    branch: 'ECE',
    year: 2022,
    semester: 5,
    exam_type: 'End-Sem',
    pdf_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    slug: 'emt-end-sem-2022-ece-s5',
    download_count: 98,
  },
  {
    title: 'VLSI Design - Mid Semester 2022',
    subject: 'VLSI Design',
    branch: 'ECE',
    year: 2022,
    semester: 7,
    exam_type: 'Mid-Sem',
    pdf_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    slug: 'vlsi-mid-sem-2022-ece-s7',
    download_count: 87,
  },
  {
    title: 'Thermodynamics - End Semester 2023',
    subject: 'Thermodynamics',
    branch: 'MECH',
    year: 2023,
    semester: 3,
    exam_type: 'End-Sem',
    pdf_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    slug: 'thermo-end-sem-2023-mech-s3',
    download_count: 167,
  },
  {
    title: 'Fluid Mechanics - Mid Semester 2023',
    subject: 'Fluid Mechanics',
    branch: 'MECH',
    year: 2023,
    semester: 5,
    exam_type: 'Mid-Sem',
    pdf_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    slug: 'fluid-mid-sem-2023-mech-s5',
    download_count: 134,
  },
  {
    title: 'Machine Design - End Semester 2022',
    subject: 'Machine Design',
    branch: 'MECH',
    year: 2022,
    semester: 6,
    exam_type: 'End-Sem',
    pdf_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    slug: 'machine-design-end-sem-2022-mech-s6',
    download_count: 115,
  },
  {
    title: 'Engineering Mathematics - Mid Semester 2023',
    subject: 'Engineering Mathematics',
    branch: 'CSE',
    year: 2023,
    semester: 1,
    exam_type: 'Mid-Sem',
    pdf_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    slug: 'engg-math-mid-sem-2023-cse-s1',
    download_count: 421,
  },
]

export const subjectTiles = [
  { name: 'Data Structures', icon: '🌲', branch: 'CSE', color: 'from-teal-400 to-teal-600' },
  { name: 'Operating Systems', icon: '⚙️', branch: 'CSE', color: 'from-blue-400 to-blue-600' },
  { name: 'Computer Networks', icon: '🌐', branch: 'CSE', color: 'from-violet-400 to-violet-600' },
  { name: 'Thermodynamics', icon: '🔥', branch: 'MECH', color: 'from-orange-400 to-orange-600' },
  { name: 'Analog Circuits', icon: '⚡', branch: 'ECE', color: 'from-yellow-400 to-yellow-600' },
  { name: 'Engineering Math', icon: '∑', branch: 'CSE', color: 'from-pink-400 to-pink-600' },
]
